### ISSUE TITLE
Revise Section 0.3 based on Overleaf feedback.

### ISSUE THREAD

**Issue by mhrmm** [Mark-Hopkins-at-Reed/thesis-hien-nguyen#26]
@yonebayashi I've made comments on your BLEU writeup. Please go through them at some point and update your manuscript accordingly.

**Comment by yonebayashi** [comment]
I made some edits! I'm a bit unsure on how to rewrite the _Sentence Brevity Penalty_ section so I left a comment under your feedback, but all other sections have been updated.
